export const hardcodedData = [
  {
    poolPair: "USDC-ETH",
    currentPotValue: "$100,000",
    ownedTickets: 10849,
    totalTickets: 100000,
    status: "active",
  },
  {
    poolPair: "ETH-DAI",
    currentPotValue: "$75,000",
    ownedTickets: 5432,
    totalTickets: 75000,
    status: "completed",
  },
  {
    poolPair: "LINK-ETH",
    currentPotValue: "$50,000",
    ownedTickets: 3210,
    totalTickets: 50000,
    status: "active",
  },
  {
    poolPair: "UNI-USDC",
    currentPotValue: "$30,000",
    ownedTickets: 2100,
    totalTickets: 30000,
    status: "closed",
  },
  {
    poolPair: "AAVE-ETH",
    currentPotValue: "$40,000",
    ownedTickets: 4567,
    totalTickets: 40000,
    status: "active",
  },
  {
    poolPair: "MATIC-USDT",
    currentPotValue: "$60,000",
    ownedTickets: 7890,
    totalTickets: 80000,
    status: "active",
  },
  {
    poolPair: "MATIC-USDC",
    currentPotValue: "$45,000",
    ownedTickets: 3456,
    totalTickets: 60000,
    status: "completed",
  },
  {
    poolPair: "DOT-ETH",
    currentPotValue: "$35,000",
    ownedTickets: 2345,
    totalTickets: 45000,
    status: "closed",
  },
  {
    poolPair: "ADA-USDT",
    currentPotValue: "$25,000",
    ownedTickets: 1234,
    totalTickets: 35000,
    status: "active",
  },
  {
    poolPair: "XRP-ETH",
    currentPotValue: "$20,000",
    ownedTickets: 987,
    totalTickets: 25000,
    status: "completed",
  },
];
